# database connection
spring:
  application:
    name: tlias-web-management

  # connection information
  datasource:
    url: jdbc.mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  #mybatis configuration
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl